### ISSUE TITLE
8 - Deploy application on Heroku.

### ISSUE THREAD

**Issue by shivamkrs89** [shivamkrs89/wheel#18]

**Comment by shivamkrs89** [comment]
@yedhink 
Deployed app link: [Shivam wheel](https://wheel-shivamkrs89.herokuapp.com)
Username: [oliver@example.com](mailto:oliver@example.com)
Password: welcome

Please review.
Thanks.

**Comment by yedhink** [comment]
@shivamkrs89 LGTM. You can mark this task as completed and continue with the next task.
